services:
  nginx:
    container_name: redes-de-computadores-2
    image:  nginx:latest
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./src:/var/www/html:ro
    environment:
      - NGINX_PORT=80
    command: ["nginx", '-g', 'daemon off;']
    
  
  
  # (existe so pq gosto de usar arch, sem nenhuma utilidade fora o ambiente linux familiar à minha pessoa)  
  # app:
  #   image: archlinux:latest
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   stdin_open: true
  #   tty: true
  #   command: /bin/bash
