services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - app
    environment:
      - PORTA=
  app:
    image: archlinux:latest
    container_name: redes-de-computadores-2
    working_dir: /workspace
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    command: /bin/bash
