services:
  proxy_reverso:
    container_name: redes-de-computadores-2
    image:  nginx:latest
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./proxy_reverso/nginx:/etc/nginx/templates:ro
      - ./proxy_reverso/src:/var/www/html:ro
    command: ["nginx", '-g', 'daemon off;']

  
  herestoyou:
    image:  nginx:latest
    ports:
      - "8081:80"
    working_dir: /var/www/html
    volumes:
      - ./herestoyou/nginx:/etc/nginx/templates:ro
      - ./herestoyou/src:/var/www/html:ro
    command: ["nginx", '-g', 'daemon off;']
    
  
  
  # (existe so pq gosto de usar arch, sem nenhuma utilidade fora o ambiente linux familiar à minha pessoa)  
  # app:
  #   image: archlinux:latest
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   stdin_open: true
  #   tty: true
  #   command: /bin/bash
